Enhance JobAggr to also have openQA job id and use it
openSUSE/qem-bot pull request #105
Opened 2022-12-23 15:12 UTC by baierjan

Use openQA job id instead of dashboard openqa_jobs.id where applicable. This will also fix unblocking incidents with openQA comment.

Reference: https://progress.opensuse.org/issues/122308

2022-12-23 20:04 UTC, Martchus approved these changes
That clears up the confusion I had on Wednesday when reading the code (https://progress.opensuse.org/issues/122308#note-4). So the ID is in fact so far *not* an openQA job ID - and somehow everybody overlooked it in the pair programming session where we added the feature to read openQA comments.

2022-12-24 08:10 UTC, okurz requested changes
I suggest you also rename the variable "job" to e.g. "job_aggr"

2022-12-24 20:49 UTC, mimi1vx approved these changes

2022-12-29 10:13 UTC, baierjan commented
> I suggest you also rename the variable "job" to e.g. "job_aggr"

I propose to solve that inside #106 together with some more (potentially dangerous) polishing/renaming.

2023-01-02 07:54 UTC, okurz approved these changes

2023-01-02 07:54 UTC, merged