pc_helper: Add tests and cleanup unused code
openSUSE/qem-bot pull request #123
Opened 2023-06-22 11:56 UTC by asmorodskyi

PR contains several commits :

    - Add ability allowing to check Public Cloud related logic outside of bot-ng
    - Drop function because it is not used anymore
    - Drop use of variable PUBLIC_CLOUD_PINT_QUERY
    - Add tests for pc_helper
    - Switch to pythonic documentation format
    - Fix logging in pc_helper 
    - Call python3 binary in officially recommended way
 

Related ticket : https://progress.opensuse.org/issues/115211

NOTE : this is second attempt of merging #121 which was reverted #122  due to exception thrown during run . Difference between #121  and this one is that in case of failure we not logging the problem in caller but only inside called function . Also I add extra commit which fixing logging within pc_helper

2023-06-22 11:58 UTC, okurz requested changes
Please

* Reference a ticket for your work
* Fix CI
* Explain what you changed in relation to your previous attempt
* Definitely link the previous attempt PR!

2023-06-22 13:23 UTC, baierjan commented on bot-ng.py
> +#!/usr/bin/env python3
That's the exact opposite of what `env-script-interpreter` rpmlint check wants.

2023-06-22 16:49 UTC, okurz commented
Please look into the discussion in https://suse.slack.com/archives/C02CANHLANP/p1687438881079609?thread_ts=1687361176.085319&cid=C02CANHLANP where we discussed backward compatible changes. If you want to stay with the current implementation regardless I suggest we merge this and the mentioned merge request when you are available for longer after that, e.g. start of a business day

2023-06-26 15:20 UTC, mimi1vx approved these changes

2023-06-27 06:37 UTC, okurz approved these changes

2023-06-27 06:38 UTC, merged