Init process of using embargoed field for Incidents
openSUSE/qem-bot pull request #128
Opened 2023-07-04 13:21 UTC by asmorodskyi

Because of usage of same data structures in two independent applications (qem-bot and qem-dashboard)
we need to do introduction of new field in several stages. At first stage we will start pushing
this field into qem-dashboard from qem-bot. So after deploying this we can than read propely
this field coming from bot

2023-07-04 13:22 UTC, okurz approved these changes

2023-07-04 15:26 UTC, Martchus reviewed
Looks like tests still need to be adapted.

2023-07-04 16:20 UTC, kraih commented
Very useful test failures, confirm that it actually works as expected.

2023-07-04 19:06 UTC, kraih requested changes
Looks like the wrong place. It should be incidents and not openQA jobs.

2023-07-07 18:04 UTC, asmorodskyi commented
> Looks like the wrong place. It should be incidents and not openQA jobs.

yes you are correct . Is it right place now ?

2023-07-10 12:35 UTC, kraih approved these changes
Does look like the right place.

2023-07-10 12:35 UTC, merged