Deduplicate handling of unversioned modules
openSUSE/qem-bot pull request #142
Opened 2023-09-26 11:55 UTC by kalikiana

The logic should be the same to avoid different behavior in the same case.

See: https://progress.opensuse.org/issues/137006

2023-09-26 13:43 UTC, kalikiana commented on tests/test_incident.py
> +    assert incident.revisions_with_fallback("aarch64", "15-SP4")
I can't figure out how to reproduce the case where we get a SLE12 with no versioning...

2023-09-26 13:47 UTC, mimi1vx commented on openqabot/types/incident.py
> +            if ver.startswith("12"):
this is wrong place , first full version check then with '12'

2023-09-26 13:52 UTC, mimi1vx requested changes

2023-09-26 13:52 UTC, mimi1vx commented on openqabot/types/incident.py
> +            if ver.startswith("12"):
something like 

```
if ArchVer(arch,ver) in self.revisions:
     return self.revisions[ArchVer(arch, ver)]
if ver.startswith("12") and ArchVer(arch, "12") in self.revisions:
      return self.revisions[ArchVer(arch, "12")]
return None
```

2023-09-26 16:20 UTC, kalikiana commented on tests/test_incident.py
> +    assert incident.revisions_with_fallback("aarch64", "15-SP4")
Works now. Typos can be confusing in this context.

2023-09-26 17:03 UTC, perlpunk approved these changes

2023-09-27 08:05 UTC, mimi1vx approved these changes

2023-09-27 08:06 UTC, merged

2023-09-27 22:05 UTC, mpagot commented on openqabot/types/incidents.py
> +                    revs = inc.revisions_with_fallback(arch, self.settings("VERSION"))
Should not be 
```
revs = inc.revisions_with_fallback(arch, self.settings["VERSION"])
```

Square bracket to accessing the **settings** dictionary?