Add coverage report to CI
openSUSE/qem-bot pull request #23
Opened 2022-04-25 12:04 UTC by mimi1vx

2022-04-25 12:37 UTC, Martchus reviewed
I'm wondering whether we really need *that* much fixtures. From my experience with openQA I'd say the risk of adding too many fixtures is slowing down tests unnecessarily and having sometimes a hard time understanding the test setup.

2022-04-25 12:46 UTC, mimi1vx commented
@Martchus fixtures are based on real data, and pretty simple :D 
*input* - what bot gets from various api
*output*  - excepted results

no need any excessive tests setup/etc because bot itself is simple stateless app which acts basically like filter -> get data from some sources , modify and then forward to target

2022-04-25 13:22 UTC, baierjan commented
> I'm wondering whether we really need _that_ much fixtures.

Using real data and known valid results would be much faster (and maybe also safer) solution than trying to create a perfect handpicked set of minimal fixtures. Not mentioning the complexity if you want to cover every possible combination of states. On the other, I am not saying it wouldn't be nice to have some "minimal working example".

I think I can live with the proposed changes.

2022-04-25 15:04 UTC, Martchus commented
The idea wasn't to craft some artificial fixtures but to strip the production data down to what's really needed. Likely many arrays in that JSON document could be way shorter without losing test coverage.

2022-04-26 09:04 UTC, okurz requested changes

2022-04-26 09:40 UTC, okurz commented on .github/workflows/ci.yml
> +          files: coverage.xml
But the thing is we should have a single command that runs tests + black. I mentioned three alternatives. You could choose one or add a fourth alternative :)

2022-04-26 09:45 UTC, Martchus commented on .github/workflows/ci.yml
> +          files: coverage.xml
I also prefer having a single command to run everything testing related (including style checks) *and* still be able to run `pytest` manually.

2022-04-26 13:03 UTC, mimi1vx commented on .github/workflows/ci.yml
> +          files: coverage.xml
> But the thing is we should have a single command that runs tests + black. I mentioned three alternatives. You could choose one or add a fourth alternative :)

why with one command ? tests and style are two different things. If is so important run it with one command .. we can add `pytest-black` plugin to requirements and run it as one ...

2022-04-26 14:19 UTC, perlpunk commented on .github/workflows/ci.yml
> +          files: coverage.xml
Having a Makefile with `test*` targets is a good language agnostic thing to get a quick overview what tests are available. Plus command line tab completion.
I don't want to remember which black, flake, doctests or whatever a certain project requires.

2022-04-26 15:11 UTC, kalikiana commented on .github/workflows/ci.yml
> +          files: coverage.xml
I second Tina's point.

2022-04-29 10:04 UTC, okurz requested changes

2022-04-29 10:04 UTC, okurz commented on Makefile
> +	black ./
I suggest to use the same style as in
https://github.com/os-autoinst/openQA/blob/master/Makefile#L139= , e.g. include style checks as part of test

2022-04-29 10:04 UTC, okurz commented on .github/workflows/ci.yml
> +          files: coverage.xml
And now please call the Makefile from here to not duplicate

2022-04-29 10:15 UTC, Martchus approved these changes

2022-04-29 10:28 UTC, okurz approved these changes

2022-04-29 10:36 UTC, merged