Correctly work with 404 error from OBS in approver
openSUSE/qem-bot pull request #36
Opened 2022-06-01 06:29 UTC by mimi1vx

2022-06-01 06:39 UTC, okurz requested changes

2022-06-01 06:39 UTC, okurz commented on openqabot/approver.py
> +                logger.error(
If qem-bot already takes the action of ignoring, why log as error?

2022-06-01 09:44 UTC, perlpunk reviewed
I think I would find it helpful to also log the url.

2022-06-01 09:47 UTC, mimi1vx commented
> I think I would find it helpful to also log the url.

URL will be pretty awful (obs api) , what will be helpful is Request number

2022-06-01 11:04 UTC, okurz requested changes

2022-06-01 11:04 UTC, okurz commented on openqabot/approver.py
> +                logger.error(
still here I would use `logger.debug` (or `logger.info`) as there is already the action mentioned that is conducted when the situation is hit. We should ask ourselves what a reader of an error log message should do. If it's nothing that needs to be done then we also don't need to log with that high level

2022-06-07 10:21 UTC, okurz approved these changes

2022-06-07 12:05 UTC, merged