Fix development group check
openSUSE/qem-bot pull request #40
Opened 2022-06-09 10:13 UTC by mimi1vx

Add perforace optimization when fetching result from openqa
Add test for IncSyncRes

2022-06-09 10:19 UTC, okurz requested changes

2022-06-09 10:19 UTC, okurz commented on openqabot/openqa.py
> +_DEVELOPMENT_PARENT_GROUP_ID = 9
I suggest to move that to __init__.py where we have other configuration settings already

2022-06-09 13:51 UTC, okurz requested changes
@mimi1vx you asked for review but seems you missed the actual suggested changes

2022-06-09 16:49 UTC, mimi1vx commented
> @mimi1vx you asked for review but seems you missed the actual suggested changes

oh, .... I forget push

2022-06-09 19:21 UTC, okurz submitted a review, later dismissed
Code looks good but please still fix the typo in the git commit message

2022-06-10 09:44 UTC, baierjan approved these changes

2022-06-10 09:52 UTC, merged