tests: Skip 'responses' test if not available on older python
openSUSE/qem-bot pull request #95
Opened 2022-12-02 09:37 UTC by okurz

2022-12-02 16:05 UTC, perlpunk approved these changes

2022-12-06 09:05 UTC, kalikiana requested changes

2022-12-06 10:28 UTC, okurz commented on tests/test_utils.py
> +
sounds nice but as we need the object "registries.OrderedRegistry" in the next line's fixture I don't see how we can use this approach.

2022-12-06 10:33 UTC, mimi1vx commented on tests/test_utils.py
> +
@kalikiana @okurz https://docs.pytest.org/en/7.1.x/how-to/skipping.html

2022-12-06 10:36 UTC, Martchus approved these changes

2022-12-06 10:44 UTC, okurz commented on tests/test_utils.py
> +
mimi1vx already approved but the one other option I see is to move the corresponding test function into another file and then execute `registries = pytest.importorskip("responses.registries")`

2022-12-06 10:53 UTC, kalikiana commented on tests/test_utils.py
> +
I would have thought you can still skip it, maybe move the fixture into the function.

If you can't I suggest at least checking the version in the import and clarifying what requirement prevents us from running that test.

2022-12-06 12:33 UTC, okurz commented on tests/test_utils.py
> +
> I would have thought you can still skip it, maybe move the fixture into the function.

I wouldn't know how

> If you can't I suggest at least checking the version in the import and clarifying what requirement prevents us from running that test.

I wouldn't know how to check the version. Many packages have an attribute `__version__` but responses doesn't. But I added a comment to explain that. Is this enough?

2022-12-06 12:40 UTC, kalikiana approved these changes

2022-12-06 12:40 UTC, kalikiana commented on tests/test_utils.py
> +
Thanks. That seems clear enough.

2022-12-06 12:41 UTC, merged